version: '3.8'

services:
  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - DATABASE_URL=sqlite:///./nimbus.db
    volumes:
      - nimbus_sqlite_data:/app/nimbus.db
      - nimbus_storage:/app/storage
    restart: always

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  nimbus_sqlite_data:
  nimbus_storage:
