version: '3.8'

services:
  backend:
    platform: linux/amd64
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - DATABASE_URL=mysql+pymysql://nimbus_user:nimbus_password@db/nimbus
    depends_on:
      - db
    restart: always

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

  db:
    platform: linux/amd64
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: nimbus
      MYSQL_USER: nimbus_user
      MYSQL_PASSWORD: nimbus_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
